#!/bin/bash

RUN_MYSQL="docker-compose run mysql mysql --host=mysql --port=3306 --protocol=tcp -uroot -pbranch"
RUN_LEMONSVC="docker-compose run lemons.api"

case "$1" in
    "schema")
        echo "dropping database"
        $RUN_MYSQL -e "DROP DATABASE IF EXISTS lemons;"
        echo "creating database"
        $RUN_MYSQL -e "CREATE DATABASE IF NOT EXISTS lemons COLLATE 'utf8_general_ci';"
        echo "creating auth schema"
        $RUN_MYSQL < ./scripts/schema/auth.sql
        ;;
    "mysql")
        docker-compose exec mysql mysql -uroot -pbranch
        ;;
    *)
        echo "Unrecognized command. Try one of: 'schema'"
        ;;
esac
