version: '3.1'
services:

  lemons.db:
    image: mysql
    container_name: lemons.db
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=branch
      - MYSQL_DATABASE=lemons

volumes:
  mysqldb:
